# Generated by Django 5.2.7 on 2025-10-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('ingredients', models.JSONField(verbose_name='Ингредиенты')),
                ('instructions', models.TextField(verbose_name='Инструкции')),
                ('servings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порции')),
                ('cook_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Время готовки (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-created_at'],
            },
        ),
    ]
