# Generated by Django 5.2.7 on 2025-10-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='signature',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Сигнатура дубликата'),
        ),
    ]
