"""
Django settings for recipes project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment in production; fall back only for local development.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-0kg6jeg(hq8ss9slek!qfd+e&tf#8x38cd3&7(ch$1ow-%_*ng')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable DEBUG=True for local dev, default False for safety.
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Allow PythonAnywhere and local hosts; override via ALLOWED_HOSTS env (comma-separated)
ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '.pythonanywhere.com,localhost,127.0.0.1').split(',') if h]

# Trust PythonAnywhere domain by default; extend via CSRF_TRUSTED_ORIGINS env (comma-separated full origins)
CSRF_TRUSTED_ORIGINS = [
    *([o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o]),
    'https://*.pythonanywhere.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recipes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'recipes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Поддержка PostgreSQL через переменные окружения, fallback на SQLite для локальной разработки
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'recipes_db'),
            'USER': os.getenv('DB_USER', 'recipes_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'recipes_password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # Fallback на SQLite для локальной разработки без Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Where collectstatic will place files for production hosting
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (for uploaded files if needed in the future)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application storage directories for JSON/XML data
# We keep separate folders for uploaded files and exported files.
DATA_ROOT = BASE_DIR / 'data'
UPLOADS_DIR = DATA_ROOT / 'uploads'
EXPORTS_DIR = DATA_ROOT / 'exports'
SINGLE_DATA_FILE = EXPORTS_DIR / 'recipes.xml'

# Ensure directories exist during startup (development-safe)
for required_dir in (MEDIA_ROOT, DATA_ROOT, UPLOADS_DIR, EXPORTS_DIR):
    required_dir.mkdir(parents=True, exist_ok=True)

# Ensure the single data file exists (empty <recipes/> by default)
try:
    if not SINGLE_DATA_FILE.exists():
        SINGLE_DATA_FILE.write_text('<?xml version="1.0" encoding="utf-8"?>\n<recipes/>', encoding='utf-8')
except Exception:
    # In development it's fine to ignore file creation errors here
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
